# Generated by Django 3.1 on 2020-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201001_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ImageField(blank=True, upload_to='home/images'),
        ),
    ]
