# Generated by Django 3.1 on 2020-10-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201001_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='', upload_to='home/images/'),
        ),
    ]
