# Generated by Django 3.1 on 2020-10-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201001_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posttype',
            field=models.CharField(default='video', max_length=10),
        ),
    ]
