# Generated by Django 3.1 on 2020-10-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201002_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='home/userProfiles'),
        ),
    ]
