# Generated by Django 3.1 on 2020-10-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_user_followed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_user',
            field=models.IntegerField(),
        ),
    ]
