# Generated by Django 3.1 on 2020-10-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201003_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_user',
        ),
    ]
