# Generated by Django 3.1 on 2020-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='raters',
            field=models.ManyToManyField(related_name='who_rated', to='home.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
