# Generated by Django 3.1 on 2020-10-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(default='', related_name='follower', to='home.User'),
        ),
        migrations.AlterField(
            model_name='following',
            name='followed',
            field=models.ManyToManyField(default='', related_name='followed', to='home.User'),
        ),
    ]
