# Generated by Django 3.1 on 2020-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20201005_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avgRating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
