# Generated by Django 3.1 on 2020-10-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_comments'),
        ('home', '0025_auto_20201005_1136'),
    ]

    operations = [
    ]
