# Generated by Django 3.1 on 2020-10-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-time']},
        ),
    ]
