# Generated by Django 3.1 on 2020-10-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_post_report'),
        ('home', '0029_auto_20201006_0038'),
    ]

    operations = [
    ]
