# Generated by Django 3.1 on 2020-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_merge_20201006_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=15),
        ),
    ]
