# Generated by Django 3.1 on 2020-10-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20201013_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
