# Generated by Django 3.1 on 2020-10-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_replies_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replies',
            options={'ordering': ['-time']},
        ),
    ]
