# Generated by Django 3.1 on 2020-10-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20201020_1630'),
        ('home', '0039_auto_20201020_1303'),
    ]

    operations = [
    ]
