# Generated by Django 3.1 on 2020-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_merge_20201021_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='getid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='which',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
