# Generated by Django 3.1 on 2020-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20201024_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='getid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='which',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
