# Generated by Django 3.1 on 2020-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20201024_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='getid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='which',
            field=models.CharField(default='', max_length=30),
        ),
    ]
