# Generated by Django 3.1 on 2020-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20201024_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
