# Generated by Django 3.1 on 2020-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='ss',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
