# Generated by Django 3.1 on 2020-10-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20201029_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['time']},
        ),
    ]
