# Generated by Django 3.1 on 2020-11-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20201029_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(default='', max_length=20)),
                ('mobile', models.IntegerField()),
                ('check_otp', models.CharField(default='', max_length=6)),
                ('otp_count', models.IntegerField(default=0)),
            ],
        ),
    ]
