# Generated by Django 3.1 on 2020-11-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paytm',
            field=models.IntegerField(default=0),
        ),
    ]
