# Generated by Django 3.1 on 2020-10-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0004_auto_20201015_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default='')),
            ],
        ),
    ]
