# Generated by Django 3.1 on 2020-10-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0005_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
