# Generated by Django 3.1 on 2020-10-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0006_auto_20201015_1208'),
        ('paytm', '0006_auto_20201015_1211'),
    ]

    operations = [
    ]
