# Generated by Django 3.1 on 2020-10-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0036_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(default='', max_length=20)),
                ('limit', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
                ('members', models.ManyToManyField(related_name='members_of_room', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=100)),
                ('by_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_whom', to='home.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_room', to='chat.room')),
            ],
        ),
    ]
