# Generated by Django 3.1 on 2020-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chats_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
