# Generated by Django 3.1 on 2020-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_post_paid'),
        ('chat', '0005_room_which'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blocked',
            field=models.ManyToManyField(related_name='blocked_users', to='home.User'),
        ),
    ]
